# Shell variables
# Generated by 'wal'
wallpaper='/home/rherault/Images/wallpapers/outer-wilds.jpeg'

# Special
background='#010102'
foreground='#9ec5ca'
cursor='#9ec5ca'

# Colors
color0='#010102'
color1='#275169'
color2='#605A59'
color3='#9D684F'
color4='#7B8265'
color5='#BEA05F'
color6='#386D8B'
color7='#9ec5ca'
color8='#6e898d'
color9='#275169'
color10='#605A59'
color11='#9D684F'
color12='#7B8265'
color13='#BEA05F'
color14='#386D8B'
color15='#9ec5ca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
