#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER='/home/rherault/Images/wallpapers/outer-wilds.jpeg'

swaybg --output '*' --mode fill --image "$WALLPAPER"
